import 'package:flutter/material.dart';

import 'menu/side_menu.dart';

class HomeScreen extends StatelessWidget {
  static const String name = 'home_screen';
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Pagina homeee'),
        automaticallyImplyLeading: false, // para que no muestre el boton de volver
      ),
      body: ListView(
        children: [
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola Mundo'),),
          Center(child: Text('Hola final'),),

        ],
      ),


      bottomNavigationBar: Text('Hola mundo end'),
      endDrawer: SideMenu(),
    );
  }
}
